version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/echo.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/by.sh
      timeout: 300
      runas: root
 
